//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPCRental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public int ID { get; set; }
        public string CName { get; set; }
        public string CEmail { get; set; }
        public string CPhone { get; set; }
        public string CMess { get; set; }
        public System.DateTime CCreate { get; set; }
    }
}
